### ISSUE TITLE
all: port shouldn't be uint16

### ISSUE THREAD

**Issue by rakyll** [census-ecosystem/opencensus-go-exporter-ocagent#21]
```
func WithPort(port uint16) ExporterOption
```

WithPort option takes an uint16 which should be just an int.

**Comment by odeke-em** [comment]
Thanks for filing this issue @rakyll!

Am not sure I agree with making a port an int: a port is a value in the range [0, 65535] which is the exact range for uint16. int can be negative or exceed 1<<16 which am not sure we want. https://en.wikipedia.org/wiki/Port_(computer_networking)
I specifically used uint16 because of the definition of a port.

What's your rationale behind this change?

**Comment by rakyll** [comment]
Yes, but languages have idiomatic types for common concepts. A port is always represented as an int in Go. See https://golang.org/pkg/net/#LookupPort.

**Comment by odeke-em** [comment]
>Yes, but languages have idiomatic types for common concepts. A port is always represented as an int in Go. See https://golang.org/pkg/net/#LookupPort.

Not really: in that same file there is a direct usage of a port with uint16 https://golang.org/pkg/net/#SRV.Port

That code returns an int because some system resolves can return a port >65536 and the underlying C resolver and parsing logic would rather return that port to the user than muck with limiting, so it seems to be more of an exception than idiomatic.

In the end though we are no longer going to use the WithPort option, for the suggestion to only keep the WithAddress option, that I agree with. Thus after WithAddress is the lone option, we won't need to have this debate :)

**Comment by songy23** [comment]
Closing - from https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/issues/22#issuecomment-428732509, we'll just remove the `withPort` method.

**Comment by HarikrishnanBalagopal** [comment]
@rakyll 
> > Not really: in that same file there is a direct usage of a port with uint16 https://golang.org/pkg/net/#SRV.Port
> 
> Because it represents a well defined SRV record where port is represented as a uint16.

No, see other places like https://pkg.go.dev/net/netip#AddrPortFrom where they have used `uint16`.
The usage of `uint16` is not limited to "a well defined SRV record".

Also here https://pkg.go.dev/net/netip#AddrPort.Port where the return value is `uint16`.

As @odeke-em mentioned already
```
That code returns an int because some system resolves can return a port >65536 and the underlying C resolver and parsing logic would rather return that port to the user than muck with limiting, so it seems to be more of an exception than idiomatic.
```
Using `int` for port is the exception not the rule. If anything it's more idiomatic to use `uint16` to represent ports.
